### ISSUE TITLE
画像フィールドのプレビューサイズを変更できるようにしたい

### ISSUE THREAD

**Issue by torounit** [inc2734/smart-custom-fields#11]
画像フィールドでアップロードした画像が大きいすぎると、ちょっと使いづらかったりします。

そんなわけで、ACFのように画像のプレビューサイズを弄れるようにした方が良いかなと思いますがどうでしょうか。

とりあえず、時間があるときにコードを書いてプルリクエスト投げます！

**Comment by inc2734** [comment]
設定項目が増えるのがイヤでもともと省いてたんですけど、実際使うと僕も不便だなーと思ってました^^; プルリク助かります！
