### ISSUE TITLE
WYSIWYGで挿入した画像のパスが書き換わる

### ISSUE THREAD

**Issue by mimosafa** [inc2734/smart-custom-fields#14]
[WordPress › フォーラム » Smart Custom Fields のWYSIWYGで挿入した画像のパスが書き換わる](https://ja.forums.wordpress.org/topic/153139)

> Smart Custom Fields のWYSIWYGエディタを使い画像を挿入したところ、src属性が書き換わる現象が起こっています。
>
> 具体的には、メディアボタンから挿入時点では、
>
> http://example.jp/wp/wp-content/uploads/2015/08/example.png
>
> となっているのが、保存ボタンを押すと、
>
> ../wp-content/uploads/2015/08/example.png
>
> に、変わってしまいます。

js/editor.js で tinymce の初期化にあたって `convert_urls` を `false` にしたら相対パスへの書き換えは起こりませんでした。(1.4.0)

**Comment by inc2734** [comment]
https://github.com/inc2734/smart-custom-fields/commit/2d3aee980e2a28bcf22a27b8b9998da086508c4f

**Comment by inc2734** [comment]
ありがとうございます！
