### ISSUE TITLE
1.5.0以降で、デフォルトで付いているエディタがテキストモードにならない。

### ISSUE THREAD

**Issue by torounit** [inc2734/smart-custom-fields#16]
1.5.0以降で、デフォルトで付いているエディタがテキストモードにならない。

管理画面にRepeatableな画像フィールドと、RepeatableでないWysiwygエディタが複数存在するものがある場合に発生するっぽい。。。

**Comment by inc2734** [comment]
5a7fa23375c5a3b0dca3ae4d27ea07885cd14273
修正できた…はず

**Comment by torounit** [comment]
直ったと思いますが、ちゃんと検証してからCloseします。
