### ISSUE TITLE
フィールドを追加するとデータが表示されなくなる

### ISSUE THREAD

**Issue by hideokamoto** [inc2734/smart-custom-fields#21]
WordPress4.3.1
Smart Custom Fields 1.6.1

フィールドを追加するとそれまでに入力したカスタムフィールドの値が表示されなくなる現象が出ています。

## 再現手順
１：管理画面左メニューより「Smart Custom Fields」＞「新規追加」を選択
２：カスタムフィールドを作成
３：２で作成したフィールドにデータを入力した記事を作成する
４：１・２の手順を繰り返し新しいフィールドを作成する
５：３で作成した記事を開くと、カスタムフィールドに入力した値が表示されなくなる

## 原因と思われる箇所
https://github.com/inc2734/smart-custom-fields/blob/master/classes/models/class.meta.php#L174-L176
フィールド（$settings）が複数ある場合、
$fieldsの値が「最後に作成されたフィールドのもの」に固定される。

## 対応
$settingsの処理無しでも値は取れている様子なので、
https://github.com/inc2734/smart-custom-fields/blob/master/classes/models/class.meta.php#L174-L176
と真下の「if ( isset( $fields[$meta_key] ) ) {」を外してもいいのかなと思います。

## その他
繰り返しフィールドとかでテストしてないんでとりあえずわかった範囲でまとめました。
一応対応に書いた内容をテスト環境で実装はしてみたんですが、
仕様理解ちょっと怪しいのでもうちょっとこちらでも試してみます。

**Comment by hideokamoto** [comment]
## 補足
フィールド作成時は手順２も手順４も「投稿」でフィールドを表示するように設定しないと再現しないかもです。

**Comment by torounit** [comment]
これはテストも書かないといけないやつだ。
