### ISSUE TITLE
通常のcontentエディタがHTMLモードの時、wysiwygエディタに画像挿入すると相対パスになる

### ISSUE THREAD

**Issue by mypacecreator** [inc2734/smart-custom-fields#23]
いつの間にか、wysiwygで作成したフィールドに入れた画像がリンク切れするようになっていたので調べてみたところ、おそらく「編集画面を開いた時に、本文エディタがHTMLモードになっている」という条件下で、挿入した画像が相対パスになってしまうようです。

バージョンは1.5.1 / 1.5.2 / 1.6.3 で確認。それ以上古いバージョンでもそうだったかは未確認です。

バグやIssueとは言いがたい現象で、知ってれば運用上困らないのですが
知らないと焦るので書いておきます。もう気づいてたらすみません^^;

**Comment by inc2734** [comment]
こちらの環境だと再現しませんね、なんでしょう。。wysiwygフィールド内の画像も表示時も相対パスですよね？
ちなみに、このテストをしていて、エディタがテキストモードの状態で編集画面を開くと、wysiwygフィールドの表示が tinymce のデフォルトのフォーマットになってしまうという不具合を見つけました…

**Comment by mypacecreator** [comment]
念のため、見せてもよいテスト環境でもやってみたら再現しました。
http://wp03.ozonenotes.jp/archives/3724

こちらはビジュアルエディタモードの状態で画面を開いて画像を入れたものです。こちらはhttp://ではじまっています。
http://wp03.ozonenotes.jp/archives/3715

相対パスになるだけじゃなくて、editor-styleが適用されてないっぽかったりもするので、

>エディタがテキストモードの状態で編集画面を開くと、wysiwygフィールドの表示が tinymce のデフォルトのフォーマットになってしまう

これと根本的には同じ問題かもしれませんね。。。

**Comment by inc2734** [comment]
> エディタがテキストモードの状態で編集画面を開くと、wysiwygフィールドの表示が tinymce のデフォルトのフォーマットになってしまう
については、修正したものを develop ブランチにプッシュしています。これで一緒に治っていてくれるとラッキーなのですが…。
https://github.com/inc2734/smart-custom-fields/tree/develop

> 相対パスになるだけじゃなくて、editor-styleが適用されてないっぽかったりもするので、
editor-style はもともと適用されないのではなかったですっけ（作者の僕が聞くのもなんですが…）

**Comment by mypacecreator** [comment]
あ、developのv1.6.4で状況改善しました！ビンゴでしたね。
↓
http://wp03.ozonenotes.jp/archives/3724

editor-styleに関してですが、言葉だと分かりづらいのでキャプチャを貼りますが

1.6.3だと
![http___wp03 ozonenotes jp_wp-admin_post php_post 3724 action edit](https://cloud.githubusercontent.com/assets/3164205/11553090/ba7c4368-99ce-11e5-8cb1-495fdeb06f7b.png)

1.6.4だと
![http___wp03 ozonenotes jp_wp-admin_post php_post 3724 action edit](https://cloud.githubusercontent.com/assets/3164205/11553099/ce050abe-99ce-11e5-96f2-fff5dedd9219.png)

こんな感じです。
上は
/wp-includes//js/tinymce/skins/lightgray/content.min.css
/wp-includes/js/tinymce/skins/wordpress/wp-content.css
の２枚が、

下はさらに
/twentyfifteen/css/editor-style.css
も適用されています。

**Comment by mypacecreator** [comment]
いろいろ書きましたが解決っぽいです:)

**Comment by inc2734** [comment]
詳しくありがとうございます！！editor-sytle 適用されるんですね（偶然の産物）
近日中にアップデートします！
