### ISSUE TITLE
echo SCF::get_term_meta( ... )が取得できない 

### ISSUE THREAD

**Issue by kitakado-h** [inc2734/smart-custom-fields#24]
1.5.2から1.6.4にアップしました。
<?php echo nl2br(esc_html( SCF::get_term_meta(  $term_id, $taxonomy,  'hoge' ,true ) ));?>
で取得、表示していたものが取得できず、この行から下が真っ白になってしまいます。
1.6.4では記述を変える必要がありますでしょうか。

**Comment by inc2734** [comment]
特に変更はしていないはずなのですが…。WP_DEBUG を true にすると何かエラーメッセージがでませんでしょうか？

**Comment by kitakado-h** [comment]
ありがとうございます。
Fatal error: Call to a member function get_group() on a non-object in /var/www/wordpress/wp-content/plugins/smart-custom-fields/classes/class.scf.php on line 163
と出ます。

**Comment by inc2734** [comment]
原因はまだわかりませんが、設定情報が正しく取得できていないような気がしますね。smart-cf-register-fields フックでカスタムフィールドを定義したりしていますか？

**Comment by kitakado-h** [comment]
別の製作者にお願いしたものなのですが、functions.phpを見る限り smart-cf-register-fields は定義されていないようです。

**Comment by inc2734** [comment]
ご確認頂きありがとうございます。定義されていないのですね。うーん、となると WordPress のバージョンとの相性問題とか、他のプラグインとの相性問題とかがあるのかもしれませんね…。
設定データの取得は
https://github.com/inc2734/smart-custom-fields/blob/master/classes/class.scf.php#L482-L494
で行われているのですが、恐らく、何らかの原因でここでデータが返ってきていないのだと思います。こちらでももう少し動作テストしてみます。

**Comment by kitakado-h** [comment]
ありがとうございます。

**Comment by inc2734** [comment]
もし原因がわかったらぜひプルリクください！その際は Contributer に追加させて頂きます！！

**Comment by kitakado-h** [comment]
ありがとうございます。少し先になってしまいますが、コチラでもいろいろ試してみます。

**Comment by kitakado-h** [comment]
調べ直したところ、カテゴリーにカスタムフィールドを配置し、single.phpで呼びだそうとしていたようで、かなり特殊な事例でした。テーマファイルの改訂で解決いたしました。ありがとうございました。
