### ISSUE TITLE
「ビジュアルリッチエディターを使用しない」環境下でWYSIWYGエディタの初期化に失敗する

### ISSUE THREAD

**Issue by alter727** [inc2734/smart-custom-fields#26]
ユーザー設定で「ビジュアルリッチエディターを使用しない」にチェックした後、WYSIWYGエディタを含む投稿画面で初期化に失敗します。
editor.js で tinymce.init( init );  する前に tinymce の存在を確認したほうがよさそうです。

**Comment by inc2734** [comment]
ご報告ありがとうございます。wysiwygまわりは詳しくなくていつも対応に困っている部分です。tinymceが存在しないときはオリジナルのtinymceを使うようにしていたつもりでしたが、「ビジュアルリッチエディターを使用しない」環境の場合だとダメだったですね…。
