### ISSUE TITLE
Repeating repeaters?

### ISSUE THREAD

**Issue by maskedcoder** [inc2734/smart-custom-fields#36]
Could you make a way for creating repeating groups as sub-fields of repeating groups? For example, I might use a repeater with the name "Locations", which has multiple locations--and one of the sub-fields is another repeating section called "Attractions" which has multiple attractions inside an individual location.

Thanks for making this great plugin!

**Comment by inc2734** [comment]
Sorry, Smart Custom Fields is not possible to create a repeater in the repeater.
