### ISSUE TITLE
Action hook `smart-cf-fields-loaded` is called too early

### ISSUE THREAD

**Issue by hanamura** [inc2734/smart-custom-fields#37]
It seems that `smart-cf-fields-loaded` is called too early. I can’t capture the hook in `functions.php`.

It may occurred by [this change](https://github.com/inc2734/smart-custom-fields/commit/76636a95c4460c238f481afd6c3155ceaaa712d7#diff-63692bc445aa8333c2ed471c958f70b0L43). The commit changes `after_setup_theme` to `plugins_loaded`.

---

アクションフックの`smart-cf-fields-loaded`が呼ばれるタイミングが早すぎるようです。`functions.php`の中でフックを利用しようとしても、すでに呼ばれた後で使えませんでした。

[このコミット](https://github.com/inc2734/smart-custom-fields/commit/76636a95c4460c238f481afd6c3155ceaaa712d7#diff-63692bc445aa8333c2ed471c958f70b0L43)で、`after_setup_theme`内でアクションを呼んでいたのを`plugins_loaded`内で呼ぶよう変更したからこうなっているようです。

**Comment by inc2734** [comment]
ありがとうございます！何か理由があってタイミングを変更した記憶があるのですがなぜだか忘れてしまいました…。検証して問題なさそうであればマージさせていただきます。
