### ISSUE TITLE
グループのデータを取得する際に、真偽値を含むと警告が出る

### ISSUE THREAD

**Issue by Uorte** [inc2734/smart-custom-fields#39]
Wordpressバージョン4.4.3でSmart Custom Fieldsバージョン 2.2.0を使用しています。
`$repeat_group = SCF::get( 'repeat-group' );
foreach ( $repeat_group as $fields ) {
//データを取得
}`
上記のコードでグループのデータを取得する際に、グループ内の項目に真偽値を含むと以下の警告が出ます。
Warning: Invalid argument supplied for foreach() in /wp-content/plugins/smart-custom-fields/classes/class.scf.php on line 254
取得しようとしているテンプレートはカスタム投稿タイプのアーカイブページです。
真偽値でなくラジオボタンに置き換えることで警告は消えましたので問題ありませんが、念のためご報告いたします。

**Comment by inc2734** [comment]
ご報告ありがとうございます！
