### ISSUE TITLE
特定条件を満たすとwysiwygエディタで<p><br>が入力されない

### ISSUE THREAD

**Issue by nzm821** [inc2734/smart-custom-fields#46]
（こちらが報告に不適切な場所でしたら申し訳ありません）

特定条件を満たすとwysiwygエディタで`<p><br>`が入力されないことを確認しました。

<hr>
■環境
WordPress  4.6.1–ja 
Smart Custom Fields バージョン 3.0.0 

<hr>
■前提条件
・フックを使って、元からある「editor」を無くす

投稿タイプ（post、page、カスタム）は関わりがありません。
カスタム投稿タイプの場合、register_post_typeのパラメータ「supports」で、
初期からあるpost、pageはremove_post_type_supportの指定で、editorを省いて試験しました。

<hr>
■現象
貴プラグインで追加した「wysiwygエディタ」欄で「ビジュアル」モードを選択し、
EnterおよびShift+Enterをkeydownした時に、自動入力されるはずの`<p><br>`が入らない。
[参考画像](https://gyazo.com/3dae0b6c59d4e29b1d68461b34e97046)

<hr>
■参考
・Chromeでコンソールを確認したところ、Javascriptのエラーは0件です。
・繰り返し処理が必要なデータ（実績、年表など）を登録したい場面があったため、
　カスタム投稿タイプをベースに、元からある「editor」を省いて、カスタムフィールドを追加。
　結果、上記の現象に気づきました。

<hr>

ほかに必要な情報があればお知らせください。

**Comment by nzm821** [comment]
なお、同様の現象にあった方のために、ざっと考えた対症療法的な解決を載せておきます。

１）もとの「editor」は表示させたうえで、function.phpに以下を追記してCSSで非表示にする
```
function admin_style_for_editor() {
	$addCss = '<style>
	#postdivrich{
		display: none;
	}
	</style>'.PHP_EOL;
		if( get_post_type() == 'customPostName' ){
		print $addCss;
	}
}
add_action('admin_enqueue_scripts', 'admin_style_for_editor');
```

２）nl2br()を使う
カスタムフィールドを表示させるとき、nl2brを使う。
※HTMLを入力したときの改行まで、brの扱いになるため注意

**Comment by inc2734** [comment]
ご報告ありがとうございます。

「ビジュアルで改行を入力し、テキストに切り替えたときに p や br が入っていない」ということであれば正常な動作だと思いますが、@nzm821 さんの環境では通常テキストに切り替えたときに p や br が入っている感じでしょうか？通常は「テキスト」には p や br は追加されず、フロントでの表示時に自動的に the_content フィルターの影響で p や br が入った状態で表示されると思います。

それとも管理画面上ではなくてフロント表示において改行が反映されないということでしょうか？

ご使用のテーマ・プラグインの影響ということも考えられますので、テーマをデフォルトテーマに戻し、Smart Custom Fields 以外の全てのプラグインを停止しても再現するのかご確認いただければと思います。

**Comment by nzm821** [comment]
早速のご確認ありがとうございます。

>通常テキストに切り替えたときに p や br が入っている

まさしくそのとおりで、管理画面上で[このような動作](https://gyazo.com/6a9543643cde0e41d24b1e1df2ed2d7a)になっています。

影響を与えそうなプラグインやfunction.phpの記述を削除してもこの動作でしたが、
手があいたときに本当にまっさらな環境で試験してみたいと思います。

お騒がせしてしまったようで申し訳ありませんでした。
