### ISSUE TITLE
Bugs of #69

### ISSUE THREAD

**Issue by inc2734** [inc2734/smart-custom-fields#71]
Hi @robssanches !

I merged #69 but I found a few bugs.

## 1
<img width="293" alt="2018-07-30 21 13 32" src="https://user-images.githubusercontent.com/1094306/43396900-1ef9fdc8-943e-11e8-9934-a0f6ca748bf5.png">

I open new smart custom field settings page, already displayed close button in Post or page Ids field. I think this is not necessary.

## 2

<img width="1071" alt="2018-07-30 21 13 49" src="https://user-images.githubusercontent.com/1094306/43397021-6edf9e1a-943e-11e8-967e-e4ebc09f95b8.png">

I focused Post or page Ids field, output JavaScript error.

Please check it when you have time. Thank you !

**Comment by robssanches** [comment]
OK Takashi, when I have a time I will fix these bugs.

Regards
