### ISSUE TITLE
PHP7, 8環境でオプションページ作成機能利用時、Warning / Fatal error が発生

### ISSUE THREAD

**Issue by mypacecreator** [inc2734/smart-custom-fields#88]
SCF::add_options_page でオプションページ作成後、$Setting->add_group でフィールド追加してオプションページにアクセスすると、PHP 7環境ではWarningが、PHP 8環境ではFatal errorが発生します。

PHP 7.3, 7.4 環境で確認
> Warning: Declaration of Smart_Custom_Fields_Controller_Option::admin_enqueue_scripts($hook) should be compatible with Smart_Custom_Fields_Controller_Base::admin_enqueue_scripts() in /(path)/wp-content/plugins/smart-custom-fields/classes/controller/class.option.php on line 27

PHP 8.0.11 環境で確認
> Fatal error: Declaration of Smart_Custom_Fields_Controller_Option::admin_enqueue_scripts($hook) must be compatible with Smart_Custom_Fields_Controller_Base::admin_enqueue_scripts() in /(path)/wp-content/plugins/smart-custom-fields/classes/controller/class.option.php on line 27

PHP 7環境ではWarningなのでDebug Mode にしなければ動作上の問題はありませんが、PHP 8環境ではFatal errorなので全く使えなくなってしまいます。

**Comment by mypacecreator** [comment]
オプションページ追加は以下のコードで対応

```
<?php
/**
 * 管理画面のメニューを作成する。
 *
 * @link https://2inc.org/blog/2016/06/06/5280/
 */
function cf_create_admin_menu() {
	/**
	 * @param string      $page_title ページのtitle属性値
	 * @param string      $menu_title 管理画面のメニューに表示するタイトル
	 * @param string      $capability メニューを操作できる権限（maange_options とか）
	 * @param string      $menu_slug  オプションページのスラッグ。ユニークな値にすること。
	 * @param string|null $icon_url   メニューに表示するアイコンの URL
	 * @param int         $position   メニューの位置
	 */
	SCF::add_options_page(
		'オプションページ',
		'オプションページ',
		'manage_options',
		'my-options',
		'dashicons-admin-settings',
		2,
	);
}

add_action( 'init', 'cf_create_admin_menu' );

/**
 * カスタムフィールドを定義
 *
 * @param array  $settings  SCF オブジェクトの配列
 * @param string $type      投稿タイプ or ロール
 * @param int    $id        投稿ID or ユーザーID
 * @param string $meta_type post | user
 *
 * @return array
 */
function register_custom_fields( $settings, $type ) {

	if ( 'my-options' !== $type ) {
		return $settings;
	}

	$Setting = SCF::add_setting( 'cf-option', 'オプションページ' );
	$Setting->add_group(
		'group-option',
		false,
		array(
                    // ここにフィールド定義いろいろ記述
		)
	);

	$settings[] = $Setting;

	return $settings;

}

add_filter( 'smart-cf-register-fields', 'register_custom_fields', 10, 2 );
```

**Comment by inc2734** [comment]
なるほど！

`smart-custom-fields/classes/controller/class.controller-base.php ` の

```
public function admin_enqueue_scripts() {
```

を

```
public function admin_enqueue_scripts( $hook ) {
```

にしたらどうでしょうか？

**Comment by mypacecreator** [comment]
@inc2734 ありがとうございます！
試してみまして、上記修正にてPHP7, 8ともにエラーが消えたことを確認しました。

よしななタイミングで修正リリースいただけましたら幸いです！
